# Generated by Django 4.0.10 on 2025-03-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act1', '0002_auto_20250317_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
