# Generated by Django 4.0.10 on 2025-03-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act1', '0004_alter_operacion_tiempo_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='disponibilidad',
            field=models.CharField(choices=[('SÍ', 'Sí'), ('NO', 'No')], default='SÍ', max_length=2),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='estado_maquina',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En uso', 'En uso'), ('En mantenimiento', 'En mantenimiento'), ('Fuera de servicio', 'Fuera de servicio')], default='Disponible', max_length=45),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono',
            field=models.BigIntegerField(unique=True),
        ),
    ]
